// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/breeds/usecase/model"

	mock "github.com/stretchr/testify/mock"
)

// BreedsUseCase is an autogenerated mock type for the BreedsUseCase type
type BreedsUseCase struct {
	mock.Mock
}

// GetBreeds provides a mock function with given fields:
func (_m *BreedsUseCase) GetBreeds() ([]model.Breed, error) {
	ret := _m.Called()

	var r0 []model.Breed
	if rf, ok := ret.Get(0).(func() []model.Breed); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Breed)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
