// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/doggos/usecase/model"

	mock "github.com/stretchr/testify/mock"

	repositories "DoggosPkg/repositories"
)

// DoggosMapper is an autogenerated mock type for the DoggosMapper type
type DoggosMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: doggos
func (_m *DoggosMapper) Map(doggos []repositories.DoggoDto) []model.Doggo {
	ret := _m.Called(doggos)

	var r0 []model.Doggo
	if rf, ok := ret.Get(0).(func([]repositories.DoggoDto) []model.Doggo); ok {
		r0 = rf(doggos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Doggo)
		}
	}

	return r0
}
