// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/repositories/cats/model"

	mock "github.com/stretchr/testify/mock"

	repositories "DoggosPkg/repositories"

	usecasemodel "DoggosPkg/pets/usecase/model"
)

// PetsMapper is an autogenerated mock type for the PetsMapper type
type PetsMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: d, c
func (_m *PetsMapper) Map(d []repositories.DoggoDto, c []model.CatDto) []usecasemodel.Pet {
	ret := _m.Called(d, c)

	var r0 []usecasemodel.Pet
	if rf, ok := ret.Get(0).(func([]repositories.DoggoDto, []model.CatDto) []usecasemodel.Pet); ok {
		r0 = rf(d, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecasemodel.Pet)
		}
	}

	return r0
}
