// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/pets/usecase/model"

	mock "github.com/stretchr/testify/mock"
)

// PetsUseCase is an autogenerated mock type for the PetsUseCase type
type PetsUseCase struct {
	mock.Mock
}

// GetPets provides a mock function with given fields: page, limit, breedID
func (_m *PetsUseCase) GetPets(page int, limit int, breedID string) ([]model.Pet, error) {
	ret := _m.Called(page, limit, breedID)

	var r0 []model.Pet
	if rf, ok := ret.Get(0).(func(int, int, string) []model.Pet); ok {
		r0 = rf(page, limit, breedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, limit, breedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
