// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/repositories/breeds/model"

	mock "github.com/stretchr/testify/mock"

	usecasemodel "DoggosPkg/breeds/usecase/model"
)

// BreedsMapper is an autogenerated mock type for the BreedsMapper type
type BreedsMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: breeds
func (_m *BreedsMapper) Map(breeds []model.BreedDto) []usecasemodel.Breed {
	ret := _m.Called(breeds)

	var r0 []usecasemodel.Breed
	if rf, ok := ret.Get(0).(func([]model.BreedDto) []usecasemodel.Breed); ok {
		r0 = rf(breeds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecasemodel.Breed)
		}
	}

	return r0
}
