// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/repositories/cats/model"

	mock "github.com/stretchr/testify/mock"
)

// CatRepository is an autogenerated mock type for the CatRepository type
type CatRepository struct {
	mock.Mock
}

// GetCats provides a mock function with given fields: page, limit, breedID
func (_m *CatRepository) GetCats(page int, limit int, breedID string) ([]model.CatDto, error) {
	ret := _m.Called(page, limit, breedID)

	var r0 []model.CatDto
	if rf, ok := ret.Get(0).(func(int, int, string) []model.CatDto); ok {
		r0 = rf(page, limit, breedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CatDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, limit, breedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
