// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "DoggosPkg/repositories/cats/model"

	mock "github.com/stretchr/testify/mock"

	usecasemodel "DoggosPkg/cats/usecase/model"
)

// CatsMapper is an autogenerated mock type for the CatsMapper type
type CatsMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: doggos
func (_m *CatsMapper) Map(doggos []model.CatDto) []usecasemodel.Cat {
	ret := _m.Called(doggos)

	var r0 []usecasemodel.Cat
	if rf, ok := ret.Get(0).(func([]model.CatDto) []usecasemodel.Cat); ok {
		r0 = rf(doggos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecasemodel.Cat)
		}
	}

	return r0
}
